import type { Plugin } from 'vite';

/** Paths (relative to the service worker scope) that must always hit the network. */
const NETWORK_ONLY_PREFIXES = ['socket.io/', 'api/'];

const SW_FILE = 'sw.js';

/** FNV-1a (32-bit), fed incrementally; enough to version the cache. */
function fnv1a(hash: number, bytes: Uint8Array): number {
  let h = hash;
  for (const b of bytes) {
    h ^= b;
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

function serviceWorkerSource(cacheName: string, base: string, urls: string[]): string {
  return `// Generated by client/pwa/swPlugin.ts — do not edit.
const CACHE = ${JSON.stringify(cacheName)};
const BASE = ${JSON.stringify(base)};
const INDEX = BASE + 'index.html';
const PRECACHE = ${JSON.stringify(urls)};
const NETWORK_ONLY = ${JSON.stringify(NETWORK_ONLY_PREFIXES.map((p) => base + p))};
const NAV_TIMEOUT_MS = 3000;

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(PRECACHE.map((url) => new Request(url, { cache: 'reload' }))))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('catan-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

// Network-first so online users get fresh HTML, but a hung network (hotspot
// with no uplink) falls back to the cached shell after NAV_TIMEOUT_MS.
async function networkFirstNavigation(request) {
  const network = fetch(request);
  network.catch(() => {});
  // Plain executor instead of Promise.withResolvers: keeps the worker valid on older iOS Safari.
  const timeout = new Promise((resolve) => setTimeout(resolve, NAV_TIMEOUT_MS));
  try {
    const res = await Promise.race([network, timeout]);
    if (res) return res;
  } catch {
    // offline: fall through to the cached shell
  }
  return (await caches.match(INDEX, { cacheName: CACHE, ignoreVary: true })) || network;
}

async function cacheFirst(request) {
  const cache = await caches.open(CACHE);
  // Servers send \`Vary: Origin\`; precache requests carry no Origin while
  // crossorigin module/style requests do, so a Vary-aware lookup would miss.
  const hit = await cache.match(request, { ignoreVary: true });
  if (hit) return hit;
  const res = await fetch(request);
  if (res.ok && res.type === 'basic') cache.put(request, res.clone());
  return res;
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (NETWORK_ONLY.some((prefix) => url.pathname.startsWith(prefix))) return;
  if (request.mode === 'navigate') {
    event.respondWith(networkFirstNavigation(request));
    return;
  }
  event.respondWith(cacheFirst(request));
});
`;
}

/**
 * Emits `sw.js` after the bundle (and the copied public dir) is on disk. The
 * worker precaches every output file, serves same-origin GETs cache-first and
 * falls back to the cached index.html for navigations, so an installed app
 * starts with no network at all. Build-only: dev never registers a worker.
 */
export function serviceWorkerPlugin(): Plugin {
  let base = '/';
  return {
    name: 'catan:service-worker',
    apply: 'build',
    enforce: 'post',
    configResolved(config) {
      base = config.base.endsWith('/') ? config.base : `${config.base}/`;
    },
    async writeBundle(options) {
      const outDir = options.dir;
      if (!outDir) throw new Error('catan:service-worker requires output.dir');
      const root = outDir.replace(/\\/g, '/').replace(/\/$/, '');

      const files: string[] = [];
      const walk = async (rel: string): Promise<void> => {
        const entries = await this.fs.readdir(rel ? `${root}/${rel}` : root, { withFileTypes: true });
        for (const entry of entries) {
          const path = rel ? `${rel}/${entry.name}` : entry.name;
          if (entry.isDirectory()) await walk(path);
          else if (entry.isFile() && path !== SW_FILE && !path.endsWith('.map')) files.push(path);
        }
      };
      await walk('');
      files.sort();

      const encoder = new TextEncoder();
      let hash = 0x811c9dc5;
      for (const file of files) {
        hash = fnv1a(hash, encoder.encode(file));
        hash = fnv1a(hash, await this.fs.readFile(`${root}/${file}`));
      }
      const cacheName = `catan-${hash.toString(16).padStart(8, '0')}`;
      const urls = files.map((file) => base + file);

      await this.fs.writeFile(`${root}/${SW_FILE}`, serviceWorkerSource(cacheName, base, urls));
      this.info(`${SW_FILE}: ${urls.length} files precached in ${cacheName}`);
    },
  };
}
